create table if not exists documents (
  id bigint generated by default as identity primary key,
  filename text not null,
  sha256 text unique,
  pages integer default 0,
  created_at timestamptz default now()
);
create table if not exists facts (
  id bigint generated by default as identity primary key,
  document_id bigint references documents(id) on delete cascade,
  page integer not null,
  fact_type text not null,
  text text not null,
  evidence text not null,
  confidence double precision default 0,
  normalized_value double precision,
  normalized_unit text,
  dates jsonb default '[]', entities jsonb default '[]', warnings jsonb default '[]'
);
create table if not exists relationships (
  id bigint generated by default as identity primary key,
  fact_a bigint references facts(id) on delete cascade,
  fact_b bigint references facts(id) on delete cascade,
  relation text not null,
  score double precision default 0,
  explanation text,
  signals jsonb default '{}'
);
create index if not exists idx_facts_document on facts(document_id);
create index if not exists idx_relationships_relation on relationships(relation);
